/*
resources uses autogenerated go giles created by go generate. If errors occur when
importing items from resources, make sure that the generation a) ran, b) succeeded.
*/
package resources

//go:generate go run ../src/internal/gen/generate-resources/main.go
