// Code generated by go generate; DO NOT EDIT

package tiles

type types int

//revive:disable:var-naming
//go:generate goenums tile_types.go
const (
	
	space_tile types = iota
	
	
	
	
	ground_ul_tile
	
	ground_um_tile
	
	ground_ur_tile
	
	ground_ml_tile
	
	ground_mm_tile
	
	ground_mr_tile
	
	ground_bl_tile
	
	ground_bm_tile
	
	ground_br_tile
	
	
	
	
	coin_tile
	
	
	
	diamond_tile
	
	
	
	heart_tile
	
	
	
	spike_tile
	
	
	
	
	door_closed_tile
	
	door_opened_tile
	
	
	
)
